### ISSUE TITLE
pathlib assumes windows if a module named nt is importable

### ISSUE THREAD

**Issue by mkomitee** [mcmtroffaes/pathlib2#12]
Having an importable module named nt doesn't necessarily mean that the system is windows. 

It may be better to use sys.platform or some similar value in sys to determine what operating system is in use.

**Comment by mcmtroffaes** [comment]
I assume you refer to:

https://github.com/mcmtroffaes/pathlib2/blob/74f3fd3/pathlib2.py#L34

pathlib2 closely follows upstream pathlib from cpython, which does the same:

https://github.com/python/cpython/blob/2b4c2c7f72d000612511f333eeb56793865ddf63/Lib/pathlib.py#L19

So if you believe there's a bug, then please post it on the [cpython bug tracker](https://bugs.python.org/), unless it's a bug that exists in pathlib2 but not in pathlib. Once it's fixed in cpython, I'll backport it here.
